# Le nom de ton pipeline — visible dans l'onglet Actions

name:  Pipeline Automatique

# DÉCLENCHEUR : Ce pipeline se lance à chaque push sur "main"

on:

  push:

    branches:

      - main
  pull_request:
    branches: [ main ]


# LES JOBS : Les tâches à exécuter

jobs:

  verifier-le-code:

    name: Tests automatiques

    runs-on: ubuntu-latest   # GitHub fournit une machine Ubuntu gratuite

    steps:

      # Étape 1 : Récupère le code du dépôt

      - name: Récupérer le code

        uses: actions/checkout@v4

      # Étape 2 : Installe Node.js

      - name:  Installer Node.js

        uses: actions/setup-node@v4

        with:

          node-version: '20'

      # Étape 3 : Installe les dépendances (jest, etc.)

      - name: Installer les dépendances

        run: npm install
      # Étape 3.1 : vérification de la qualité du code
      - name: Vérification qualité du code (ESLint)
        run: npm run lint

      # Étape 4 : Lance les tests

      - name: Lancer les tests

        run: npm test

      # Étape Mutation Testing
      - name: Exécuter Stryker (Mutation Testing)
        run: npx stryker run
        # Le build s'arrêtera ici si le score < 70% grâce au "break" dans la config

      # Étape d'archivage du rapport (s'exécute même si Stryker échoue pour voir les résultats)
      - name: Sauvegarder le rapport de mutation
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapport-mutation-stryker
          path: reports/stryker/
          retention-days: 7

      # Étape 5 : Message de succès

      - name: Mission accomplie

        run: echo "Tous les tests sont au vert. L'Architecte est satisfait."

      # Étape 6 : envoyer un message

      - name : notification dans le chat
        if: failure()
        run: |
          curl -X POST "${{ secrets.GOOGLE_CHAT_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
                "text": "Échec du pipeline GitHub Actions\n\nRepo: '${{ github.repository }}'\nBranche: '${{ github.ref_name }}'\n\nVoir le détail: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }' 
